filter:
  excluded_paths:
    - 'tests/'
  dependency_paths:
    - 'vendor/'

build:
  image: default-bionic
  dependencies:
    override:
      - composer update --no-interaction --prefer-dist --ignore-platform-req=ext-zip
  nodes:
    analysis: # see https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/
      project_setup: { override: true }
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

tools:
  external_code_coverage: true
