language: php

# php compatibility
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
  - travis_retry composer require --no-interaction --prefer-dist --dev scrutinizer/ocular

script:
  - mkdir -p build/tests/
  - vendor/bin/phpcs -sp src/ tests/
  - vendor/bin/php-cs-fixer fix --using-cache=no --dry-run --verbose
  - vendor/bin/phpunit --coverage-text --coverage-clover=build/tests/coverage.xml

after_script:
  - if [[ $TRAVIS_PHP_VERSION == '7.4' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover build/tests/coverage.xml; fi

notifications:
  email: false
